export const sharedToolPageStyles = {
  stackSmall: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    marginTop: "10px",
  },
  label: {
    display: "block",
    fontSize: "14px",
    fontWeight: 600,
    color: "#e2e8f0",
    marginBottom: "8px",
  },
  labelInline: {
    fontSize: "14px",
    fontWeight: 600,
    color: "#e2e8f0",
  },
  value: {
    fontSize: "14px",
    color: "#94a3b8",
  },
  fileInput: {
    display: "block",
    width: "100%",
    boxSizing: "border-box",
    padding: "12px",
    borderRadius: "16px",
    border: "1px solid #334155",
    background: "#020617",
    color: "#e2e8f0",
    fontSize: "14px",
  },
  range: {
    width: "100%",
    marginTop: "6px",
  },
  mutedTip: {
    marginTop: "8px",
    fontSize: "12px",
    lineHeight: 1.6,
    color: "#94a3b8",
  },
  smallMuted: {
    fontSize: "12px",
    color: "#94a3b8",
  },
  rowBetween: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "12px",
  },
  modeGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    gap: "8px",
  },
  modeButton: {
    padding: "10px 12px",
    borderRadius: "14px",
    fontSize: "14px",
    fontWeight: 600,
    cursor: "pointer",
    transition: "all 0.2s ease",
  },
  modeButtonActive: {
    background: "#f8fafc",
    color: "#0f172a",
    border: "1px solid #f8fafc",
  },
  modeButtonIdle: {
    background: "#020617",
    color: "#e2e8f0",
    border: "1px solid #334155",
  },
  buttonGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: "8px",
  },
  primaryButton: {
    padding: "12px 14px",
    borderRadius: "16px",
    border: "1px solid transparent",
    background: "#34d399",
    color: "#082f49",
    fontSize: "14px",
    fontWeight: 700,
    cursor: "pointer",
  },
  infoButton: {
    padding: "12px 14px",
    borderRadius: "16px",
    border: "1px solid transparent",
    background: "#38bdf8",
    color: "#082f49",
    fontSize: "14px",
    fontWeight: 700,
    cursor: "pointer",
  },
  secondaryButton: {
    padding: "12px 14px",
    borderRadius: "16px",
    border: "1px solid #334155",
    background: "#020617",
    color: "#e2e8f0",
    fontSize: "14px",
    fontWeight: 700,
    cursor: "pointer",
  },
  buttonDisabled: {
    opacity: 0.5,
    cursor: "not-allowed",
  },
  infoCard: {
    padding: "14px",
    borderRadius: "16px",
    border: "1px solid #1e293b",
    background: "#020617",
  },
  infoTitle: {
    fontSize: "14px",
    fontWeight: 700,
    color: "#f8fafc",
    marginBottom: "6px",
  },
  infoBody: {
    fontSize: "14px",
    lineHeight: 1.6,
    color: "#cbd5e1",
  },
  testItem: {
    padding: "10px 12px",
    borderRadius: "12px",
    border: "1px solid #1e293b",
    background: "rgba(15,23,42,0.72)",
    fontSize: "12px",
    lineHeight: 1.5,
  },
  testDetails: {
    marginTop: "6px",
    color: "#94a3b8",
  },
  passText: {
    color: "#86efac",
    fontWeight: 700,
  },
  failText: {
    color: "#fda4af",
    fontWeight: 700,
  },
  canvasCard: {
    borderRadius: "24px",
    border: "1px solid #1e293b",
    background: "rgba(15,23,42,0.88)",
    padding: "16px",
    boxShadow: "0 20px 60px rgba(0,0,0,0.32)",
  },
  canvasTitle: {
    marginBottom: "12px",
    fontSize: "14px",
    fontWeight: 700,
    color: "#e2e8f0",
  },
  canvasScrollerDark: {
    overflow: "auto",
    borderRadius: "18px",
    border: "1px solid #1e293b",
    background: "#020617",
    padding: "12px",
  },
  canvasScroller: {
    overflow: "auto",
    borderRadius: "18px",
    border: "1px solid #1e293b",
    padding: "12px",
  },
  canvasElement: {
    display: "block",
    margin: "0 auto",
    maxWidth: "100%",
    maxHeight: "70vh",
    borderRadius: "12px",
    boxShadow: "0 12px 30px rgba(0,0,0,0.28)",
  },
};
